### Teste API restclient Listagem de produtos
GET http://localhost:5088/produto/listar

### Teste API restclient busca de produtos
GET http://localhost:5088/produto/buscar/Celular


### Teste API restclient Cadastro de produtos
POST http://localhost:5088/produto/cadastrar/
Content-Type: application/json

{
  "Nome": "Pao",
  "Descricao": "Alimento",
  "Preco": 5
}

### Teste cadastro novo
POST http://localhost:5088/produto/cadastrar/arroz/alimento/10



