### Teste API restclient Listagem de produtos
GET http://localhost:5088/produto/listar

### Teste API restclient busca de produtos
GET http://localhost:5088/produto/buscar/

### TESDE DELETE

DELETE http://localhost:5088/produto/deletar/

### Teste API restclient Cadastro de produtos
POST http://localhost:5088/produto/cadastrar/
Content-Type: application/json

{
  "Nome": "Pão",
  "Descricao": "Alimento",
  "Valor": 0
}


### TESTE DE PUT

PUT http://localhost:5088/produto/alterar/

{
    "Nome": "Novo Produto",
    "Descricao": "Nova Descrição",
    "Valor": 15.99
}